name: volt
description: Revolt Bot API for Dart.
version: 1.0.0

environment:
    sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
    lints: ^1.0.1
    test: ^1.16.0
dependencies:
    http: ^0.13.3
    web_socket_channel: ^2.1.0
